export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_BOOK = 'DELETE_BOOK';
export const CLEAR_CART = 'CLEAR_CART';
export const DECREASE_QUANTITY_BOOK = 'DECREASE_QUANTITY_BOOK';
export const INCREASE_QUANTITY_BOOK = 'INCREASE_QUANTITY_BOOK';
